/* === VIVENTIUM START === Thin adapter for the typed GlassHive orchestration contract. === VIVENTIUM END === */

const {
  CONVERSATION_ORCHESTRATION_TOOLS,
  DELEGATION_TOOL_NAME,
  ACTIVE_WORK_ACTION_DESCRIPTION,
  ACTIVE_WORK_ACTION_SEMANTICS,
  ACTIVE_WORK_ACTION_JSON_SCHEMA,
  ACTIVE_WORK_LIST_DESCRIPTION,
  ACTIVE_WORK_LIST_JSON_SCHEMA,
  MAIN_DELEGATION_DESCRIPTION,
  MAIN_DELEGATION_JSON_SCHEMA,
  MAIN_DELEGATION_PROFILES,
  MAIN_DELEGATION_RESOURCE_CLASSES,
  MAIN_DELEGATION_STRING_LIMITS,
  canonicalConversationOrchestrationArguments,
  hasTrustedKnownWork,
  isDeclaredConversationOrchestrator,
  isConversationOrchestrationControlTool,
  isConversationOrchestrationMutationTool,
  isConversationOrchestrationTool,
  mainDelegationTurnTruth,
  mainOrchestrationInvocationIdentity,
  recordMainDelegationOutcome,
} = require('@librechat/api');

module.exports = {
  CONVERSATION_ORCHESTRATION_TOOLS,
  DELEGATION_TOOL_NAME,
  ACTIVE_WORK_ACTION_DESCRIPTION,
  ACTIVE_WORK_ACTION_SEMANTICS,
  ACTIVE_WORK_ACTION_JSON_SCHEMA,
  ACTIVE_WORK_LIST_DESCRIPTION,
  ACTIVE_WORK_LIST_JSON_SCHEMA,
  MAIN_DELEGATION_DESCRIPTION,
  MAIN_DELEGATION_JSON_SCHEMA,
  MAIN_DELEGATION_PROFILES,
  MAIN_DELEGATION_RESOURCE_CLASSES,
  MAIN_DELEGATION_STRING_LIMITS,
  canonicalConversationOrchestrationArguments,
  hasTrustedKnownWork,
  isDeclaredConversationOrchestrator,
  isConversationOrchestrationControlTool,
  isConversationOrchestrationMutationTool,
  isConversationOrchestrationTool,
  mainDelegationTurnTruth,
  mainOrchestrationInvocationIdentity,
  recordMainDelegationOutcome,
};
