/* === VIVENTIUM START === Thin legacy adapter for typed trusted interaction provenance. === */
const {
  attachInteractionContextMetadata,
  attachLogicalTurnMetadata,
  bindCanonicalInteractionConversation,
  bindInteractionSourceSegments,
  bindLogicalTurnContext,
  buildTelegramSourceEventId,
  buildTelegramSourceOrderScope,
  createSchedulerInteractionContext,
  createTelegramInteractionContext,
  createVoiceInteractionContext,
  createWebInteractionContext,
  getTrustedAdapterCapabilities,
  getTrustedDeliveryPolicy,
  getTrustedInteractionContext,
  interactionContextMetadata,
  isInternalOrigin,
  isTrustedInternalMessage,
  normalizeAdapterCapabilities,
  normalizeDeliveryPolicy,
  normalizeInteractionContext,
  normalizeInteractionReplyContext,
  normalizeInteractionSourceSegments,
  projectTrustedClientPresentation,
  setTrustedInteractionContext,
  shouldSkipAutomaticMemoryWriter,
  shouldSkipEmotionalReaction,
  trustedLoopbackWebPresentation,
} = require('@librechat/api');

module.exports = {
  attachInteractionContextMetadata,
  attachLogicalTurnMetadata,
  bindCanonicalInteractionConversation,
  bindInteractionSourceSegments,
  bindLogicalTurnContext,
  buildTelegramSourceEventId,
  buildTelegramSourceOrderScope,
  createSchedulerInteractionContext,
  createTelegramInteractionContext,
  createVoiceInteractionContext,
  createWebInteractionContext,
  getTrustedAdapterCapabilities,
  getTrustedDeliveryPolicy,
  getTrustedInteractionContext,
  interactionContextMetadata,
  isInternalOrigin,
  isTrustedInternalMessage,
  normalizeAdapterCapabilities,
  normalizeDeliveryPolicy,
  normalizeInteractionContext,
  normalizeInteractionReplyContext,
  normalizeInteractionSourceSegments,
  projectTrustedClientPresentation,
  setTrustedInteractionContext,
  shouldSkipAutomaticMemoryWriter,
  shouldSkipEmotionalReaction,
  trustedLoopbackWebPresentation,
};
/* === VIVENTIUM END === */
